INSERT INTO users (full_name, email, password) 
VALUES ('Alice Smith', 'asmith@gmail.com', 'password')
INSERT INTO users (full_name, email, password) 
VALUES ('Scott Anderson', 'anders@hotmail.com', 'password')
INSERT INTO users (full_name, email, password) 
VALUES ('Jane Doe', 'jdoe@ymail.com', 'password')
INSERT INTO users (full_name, email, password) 
VALUES ('Willam Jackson', 'willyj@yahoo.com', 'password')