INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('bug fix', 'Login button not working', 'high', 'pending', 1, 1)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('feature update', 'Edit long URL', 'medium', 'open', 1, 2)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('feature request', 'add character counter', 'low', 'resolved', 2, 1)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('page build', 'add about us page', 'high', 'open', 3, 3)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('feature request soldout badge', 'include soldout badge on product image', 'medium', 'pending', 2, 3)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('bug total spots remaining', 'spots remaining updating on appointment error', 'high', 'open', 4, 4)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('feature add confirmation', 'upon delelting appointment ask user for confirmation', 'low', 'resolved', 2, 4)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('bug incorrect answer', 'question 1 answer is incorrect', 'high', 'open', 3, 5)
INSERT INTO tickets (name, description, priority, status, user_id, project_id)
VALUES ('feature add question', 'add question button so users can add question to quiz', 'medium', 'resolved', 4, 5)