INSERT INTO comments (note, user_id, ticket_id)
VALUES ('working on backend functionality of button', 2, 1)
INSERT INTO comments (note, user_id, ticket_id)
VALUES ('will start working on this asap', 1, 2)
INSERT INTO comments (note, user_id, ticket_id)
VALUES ('character counter functioning and tested -- complete', 3, 3)
INSERT INTO comments (note, user_id, ticket_id)
VALUES ('adding navbar link to about page', 4, 4)
INSERT INTO comments (note, user_id, ticket_id)
VALUES ('working on css for soldout badge', 1, 5)

