INSERT INTO user_project (user_id, project_id)
VALUES (1, 1)
INSERT INTO user_project (user_id, project_id)
VALUES (1, 2)
INSERT INTO user_project (user_id, project_id)
VALUES (2, 1)
INSERT INTO user_project (user_id, project_id)
VALUES (3, 3)
INSERT INTO user_project (user_id, project_id)
VALUES (2, 3)
INSERT INTO user_project (user_id, project_id)
VALUES (4, 4)
INSERT INTO user_project (user_id, project_id)
VALUES (2, 4)
INSERT INTO user_project (user_id, project_id)
VALUES (3, 5)
INSERT INTO user_project (user_id, project_id)
VALUES (4, 5)