DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT NOW()
);