DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'Open',
    date_created TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);