DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE comments(
    id SERIAL PRIMARY KEY NOT NULL,
    note TEXT NOT NULL,
    date_created TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    ticket_id INTEGER REFERENCES tickets(id) ON DELETE CASCADE
);